#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

# start the language server for development
pyls --tcp -v --host=0.0.0.0 --port=2087 &

#start the dev server
python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000
