# Generated by Django 2.0.10 on 2019-02-10 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chuckwagon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationregex',
            options={'verbose_name_plural': 'location regexes'},
        ),
        migrations.AddField(
            model_name='trucklocation',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='date',
            field=models.DateField(editable=False),
        ),
    ]
